package org.napharcos.gameloopcodmkeymap

const val key = "Key"
const val code = "code"
const val CODE = "Code"
const val name = "Name"

const val lockMouseKey = "lockMouseKey"
const val fullScreenKey = "fullScreenKey"
const val tabKey = "tabKey"
const val shiftKey = "shiftKey"
const val escKey = "escKey"
const val spaceKey = "spaceKey"
const val key1 = "1Key"
const val key2 = "2Key"
const val key3 = "3Key"
const val key4 = "4Key"
const val key5 = "5Key"
const val key6 = "6Key"
const val key7 = "7Key"
const val bKey = "bKey"
const val cKey = "cKey"
const val eKey = "eKey"
const val fKey = "fKey"
const val gKey = "gKey"
const val hKey = "hKey"
const val mKey = "mKey"
const val qKey = "qKey"
const val rKey = "rKey"
const val vKey = "vKey"
const val yKey = "yKey"
const val zKey = "zKey"
const val f4Key = "f4Key"
const val oKey = "oKey"
const val iKey = "iKey"
const val ctrlKey = "ctrlKey"
const val xKey = "xKey"
const val tKey = "tKey"
const val altKey = "altKey"
const val capsKey = "capsKey"

const val startTimes = "StartTimes=\""
const val modeId = "ModeID=\""
const val enableTips = "EnableTips=\""
const val gameKeyDT = "EnableGameKeyDT=\""
const val tipsTransparent = "TipsTransparent=\""
const val Lightness = "Lightness=\""
const val enableSwitch = "EnableSwitchViewLockMethod=\""
const val end = "\""

const val START = "startText"
const val END = "endText"

const val BR = "br"
const val DMZ = "dmz"
const val GD = "gd"